// <auto-generated />
using System;
using InstitutoWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InstitutoWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180807161740_TablaCarreras")]
    partial class TablaCarreras
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InstitutoWebApp.Models.Carreras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreCarrera")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Carreras");
                });

            modelBuilder.Entity("InstitutoWebApp.Models.Estudiantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarrerasId");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Edad");

                    b.Property<int>("IdCarreras");

                    b.Property<string>("IdCedula")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<string>("Nombre")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CarrerasId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("InstitutoWebApp.Models.Estudiantes", b =>
                {
                    b.HasOne("InstitutoWebApp.Models.Carreras", "Carreras")
                        .WithMany("Estudiantes")
                        .HasForeignKey("CarrerasId");
                });
#pragma warning restore 612, 618
        }
    }
}
